// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package org.pytorch.serve.grpc.inference.inference

object InferenceProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    com.google.protobuf.empty.EmptyProto,
    com.google.rpc.status.StatusProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      org.pytorch.serve.grpc.inference.inference.PredictionsRequest,
      org.pytorch.serve.grpc.inference.inference.PredictionResponse,
      org.pytorch.serve.grpc.inference.inference.TorchServeHealthResponse
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """Cg9pbmZlcmVuY2UucHJvdG8SIG9yZy5weXRvcmNoLnNlcnZlLmdycGMuaW5mZXJlbmNlGhtnb29nbGUvcHJvdG9idWYvZW1wd
  HkucHJvdG8aDHN0YXR1cy5wcm90byL1AgoSUHJlZGljdGlvbnNSZXF1ZXN0Ei0KCm1vZGVsX25hbWUYASABKAlCDuI/CxIJbW9kZ
  WxOYW1lUgltb2RlbE5hbWUSNgoNbW9kZWxfdmVyc2lvbhgCIAEoCUIR4j8OEgxtb2RlbFZlcnNpb25SDG1vZGVsVmVyc2lvbhJhC
  gVpbnB1dBgDIAMoCzI/Lm9yZy5weXRvcmNoLnNlcnZlLmdycGMuaW5mZXJlbmNlLlByZWRpY3Rpb25zUmVxdWVzdC5JbnB1dEVud
  HJ5QgriPwcSBWlucHV0UgVpbnB1dBI1CgtzZXF1ZW5jZV9pZBgEIAEoCUIP4j8MEgpzZXF1ZW5jZUlkSABSCnNlcXVlbmNlSWSIA
  QEaTgoKSW5wdXRFbnRyeRIaCgNrZXkYASABKAlCCOI/BRIDa2V5UgNrZXkSIAoFdmFsdWUYAiABKAxCCuI/BxIFdmFsdWVSBXZhb
  HVlOgI4AUIOCgxfc2VxdWVuY2VfaWQi1QEKElByZWRpY3Rpb25SZXNwb25zZRIvCgpwcmVkaWN0aW9uGAEgASgMQg/iPwwSCnByZ
  WRpY3Rpb25SCnByZWRpY3Rpb24SNQoLc2VxdWVuY2VfaWQYAiABKAlCD+I/DBIKc2VxdWVuY2VJZEgAUgpzZXF1ZW5jZUlkiAEBE
  jwKBnN0YXR1cxgDIAEoCzISLmdvb2dsZS5ycGMuU3RhdHVzQgviPwgSBnN0YXR1c0gBUgZzdGF0dXOIAQFCDgoMX3NlcXVlbmNlX
  2lkQgkKB19zdGF0dXMiPwoYVG9yY2hTZXJ2ZUhlYWx0aFJlc3BvbnNlEiMKBmhlYWx0aBgBIAEoCUIL4j8IEgZoZWFsdGhSBmhlY
  Wx0aDKABAoUSW5mZXJlbmNlQVBJc1NlcnZpY2USXAoEUGluZxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRo6Lm9yZy5weXRvcmNoL
  nNlcnZlLmdycGMuaW5mZXJlbmNlLlRvcmNoU2VydmVIZWFsdGhSZXNwb25zZSIAEnsKC1ByZWRpY3Rpb25zEjQub3JnLnB5dG9yY
  2guc2VydmUuZ3JwYy5pbmZlcmVuY2UuUHJlZGljdGlvbnNSZXF1ZXN0GjQub3JnLnB5dG9yY2guc2VydmUuZ3JwYy5pbmZlcmVuY
  2UuUHJlZGljdGlvblJlc3BvbnNlIgASgwEKEVN0cmVhbVByZWRpY3Rpb25zEjQub3JnLnB5dG9yY2guc2VydmUuZ3JwYy5pbmZlc
  mVuY2UuUHJlZGljdGlvbnNSZXF1ZXN0GjQub3JnLnB5dG9yY2guc2VydmUuZ3JwYy5pbmZlcmVuY2UuUHJlZGljdGlvblJlc3Bvb
  nNlIgAwARKGAQoSU3RyZWFtUHJlZGljdGlvbnMyEjQub3JnLnB5dG9yY2guc2VydmUuZ3JwYy5pbmZlcmVuY2UuUHJlZGljdGlvb
  nNSZXF1ZXN0GjQub3JnLnB5dG9yY2guc2VydmUuZ3JwYy5pbmZlcmVuY2UuUHJlZGljdGlvblJlc3BvbnNlIgAoATABQgJQAWIGc
  HJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      com.google.protobuf.empty.EmptyProto.javaDescriptor,
      com.google.rpc.status.StatusProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}