// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!

package org.pytorch.serve.grpc.openinference.open_inference_grpc

/** @param modelName
  *   The name of the model used for inference.
  * @param modelVersion
  *   The version of the model used for inference.
  * @param id
  *   The id of the inference request if one was specified.
  * @param parameters
  *   Optional inference response parameters.
  * @param outputs
  *   The output tensors holding inference results.
  * @param rawOutputContents
  *   The data contained in an output tensor can be represented in
  *   "raw" bytes form or in the repeated type that matches the
  *   tensor's data type. To use the raw representation 'raw_output_contents'
  *   must be initialized with data for each tensor in the same order as
  *   'outputs'. For each tensor, the size of this content must match
  *   what is expected by the tensor's shape and data type. The raw
  *   data must be the flattened, one-dimensional, row-major order of
  *   the tensor elements without any stride or padding between the
  *   elements. Note that the FP16 and BF16 data types must be represented as
  *   raw content as there is no specific data type for a 16-bit float type.
  *  
  *   If this field is specified then InferOutputTensor::contents must
  *   not be specified for any output tensor.
  */
@SerialVersionUID(0L)
final case class ModelInferResponse(
    modelName: _root_.scala.Predef.String = "",
    modelVersion: _root_.scala.Predef.String = "",
    id: _root_.scala.Predef.String = "",
    parameters: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = _root_.scala.collection.immutable.Map.empty,
    outputs: _root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor] = _root_.scala.Seq.empty,
    rawOutputContents: _root_.scala.Seq[_root_.com.google.protobuf.ByteString] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ModelInferResponse] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = modelName
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = modelVersion
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = id
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      parameters.foreach { __item =>
        val __value = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse._typemapper_parameters.toBase(__item)
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      outputs.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      rawOutputContents.foreach { __item =>
        val __value = __item
        __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(6, __value)
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = modelName
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = modelVersion
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = id
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      parameters.foreach { __v =>
        val __m = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse._typemapper_parameters.toBase(__v)
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      outputs.foreach { __v =>
        val __m = __v
        _output__.writeTag(5, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      rawOutputContents.foreach { __v =>
        val __m = __v
        _output__.writeBytes(6, __m)
      };
      unknownFields.writeTo(_output__)
    }
    def withModelName(__v: _root_.scala.Predef.String): ModelInferResponse = copy(modelName = __v)
    def withModelVersion(__v: _root_.scala.Predef.String): ModelInferResponse = copy(modelVersion = __v)
    def withId(__v: _root_.scala.Predef.String): ModelInferResponse = copy(id = __v)
    def clearParameters = copy(parameters = _root_.scala.collection.immutable.Map.empty)
    def addParameters(__vs: (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter) *): ModelInferResponse = addAllParameters(__vs)
    def addAllParameters(__vs: Iterable[(_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)]): ModelInferResponse = copy(parameters = parameters ++ __vs)
    def withParameters(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]): ModelInferResponse = copy(parameters = __v)
    def clearOutputs = copy(outputs = _root_.scala.Seq.empty)
    def addOutputs(__vs: org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor *): ModelInferResponse = addAllOutputs(__vs)
    def addAllOutputs(__vs: Iterable[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor]): ModelInferResponse = copy(outputs = outputs ++ __vs)
    def withOutputs(__v: _root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor]): ModelInferResponse = copy(outputs = __v)
    def clearRawOutputContents = copy(rawOutputContents = _root_.scala.Seq.empty)
    def addRawOutputContents(__vs: _root_.com.google.protobuf.ByteString *): ModelInferResponse = addAllRawOutputContents(__vs)
    def addAllRawOutputContents(__vs: Iterable[_root_.com.google.protobuf.ByteString]): ModelInferResponse = copy(rawOutputContents = rawOutputContents ++ __vs)
    def withRawOutputContents(__v: _root_.scala.Seq[_root_.com.google.protobuf.ByteString]): ModelInferResponse = copy(rawOutputContents = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = modelName
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = modelVersion
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = id
          if (__t != "") __t else null
        }
        case 4 => parameters.iterator.map(org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse._typemapper_parameters.toBase(_)).toSeq
        case 5 => outputs
        case 6 => rawOutputContents
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(modelName)
        case 2 => _root_.scalapb.descriptors.PString(modelVersion)
        case 3 => _root_.scalapb.descriptors.PString(id)
        case 4 => _root_.scalapb.descriptors.PRepeated(parameters.iterator.map(org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse._typemapper_parameters.toBase(_).toPMessage).toVector)
        case 5 => _root_.scalapb.descriptors.PRepeated(outputs.iterator.map(_.toPMessage).toVector)
        case 6 => _root_.scalapb.descriptors.PRepeated(rawOutputContents.iterator.map(_root_.scalapb.descriptors.PByteString(_)).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.type = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse
    // @@protoc_insertion_point(GeneratedMessage[org.pytorch.serve.grpc.openinference.ModelInferResponse])
}

object ModelInferResponse extends scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse = {
    var __modelName: _root_.scala.Predef.String = ""
    var __modelVersion: _root_.scala.Predef.String = ""
    var __id: _root_.scala.Predef.String = ""
    val __parameters: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]
    val __outputs: _root_.scala.collection.immutable.VectorBuilder[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor] = new _root_.scala.collection.immutable.VectorBuilder[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor]
    val __rawOutputContents: _root_.scala.collection.immutable.VectorBuilder[_root_.com.google.protobuf.ByteString] = new _root_.scala.collection.immutable.VectorBuilder[_root_.com.google.protobuf.ByteString]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __modelName = _input__.readStringRequireUtf8()
        case 18 =>
          __modelVersion = _input__.readStringRequireUtf8()
        case 26 =>
          __id = _input__.readStringRequireUtf8()
        case 34 =>
          __parameters += org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse._typemapper_parameters.toCustom(_root_.scalapb.LiteParser.readMessage[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry](_input__))
        case 42 =>
          __outputs += _root_.scalapb.LiteParser.readMessage[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor](_input__)
        case 50 =>
          __rawOutputContents += _input__.readBytes()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse(
        modelName = __modelName,
        modelVersion = __modelVersion,
        id = __id,
        parameters = __parameters.result(),
        outputs = __outputs.result(),
        rawOutputContents = __rawOutputContents.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse(
        modelName = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        modelVersion = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        id = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        parameters = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse._typemapper_parameters.toCustom(_)).toMap,
        outputs = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).map(_.as[_root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor]]).getOrElse(_root_.scala.Seq.empty),
        rawOutputContents = __fieldsMap.get(scalaDescriptor.findFieldByNumber(6).get).map(_.as[_root_.scala.Seq[_root_.com.google.protobuf.ByteString]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.OpenInferenceGrpcProto.javaDescriptor.getMessageTypes().get(11)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.OpenInferenceGrpcProto.scalaDescriptor.messages(11)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry
      case 5 => __out = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
      _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor,
      _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse(
    modelName = "",
    modelVersion = "",
    id = "",
    parameters = _root_.scala.collection.immutable.Map.empty,
    outputs = _root_.scala.Seq.empty,
    rawOutputContents = _root_.scala.Seq.empty
  )
  /** An output tensor returned for an inference request.
    *
    * @param name
    *   The tensor name.
    * @param datatype
    *   The tensor data type.
    * @param shape
    *   The tensor shape.
    * @param parameters
    *   Optional output tensor parameters.
    * @param contents
    *   The tensor contents using a data-type format. This field must
    *   not be specified if "raw" tensor contents are being used for
    *   the inference response.
    */
  @SerialVersionUID(0L)
  final case class InferOutputTensor(
      name: _root_.scala.Predef.String = "",
      datatype: _root_.scala.Predef.String = "",
      shape: _root_.scala.Seq[_root_.scala.Long] = _root_.scala.Seq.empty,
      parameters: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = _root_.scala.collection.immutable.Map.empty,
      contents: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[InferOutputTensor] {
      private[this] def shapeSerializedSize = {
        if (__shapeSerializedSizeField == 0) __shapeSerializedSizeField = {
          var __s: _root_.scala.Int = 0
          shape.foreach(__i => __s += _root_.com.google.protobuf.CodedOutputStream.computeInt64SizeNoTag(__i))
          __s
        }
        __shapeSerializedSizeField
      }
      @transient private[this] var __shapeSerializedSizeField: _root_.scala.Int = 0
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = name
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        
        {
          val __value = datatype
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
          }
        };
        if (shape.nonEmpty) {
          val __localsize = shapeSerializedSize
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__localsize) + __localsize
        }
        parameters.foreach { __item =>
          val __value = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor._typemapper_parameters.toBase(__item)
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        }
        if (contents.isDefined) {
          val __value = contents.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = name
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        {
          val __v = datatype
          if (!__v.isEmpty) {
            _output__.writeString(2, __v)
          }
        };
        if (shape.nonEmpty) {
          _output__.writeTag(3, 2)
          _output__.writeUInt32NoTag(shapeSerializedSize)
          shape.foreach(_output__.writeInt64NoTag)
        };
        parameters.foreach { __v =>
          val __m = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor._typemapper_parameters.toBase(__v)
          _output__.writeTag(4, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        contents.foreach { __v =>
          val __m = __v
          _output__.writeTag(5, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withName(__v: _root_.scala.Predef.String): InferOutputTensor = copy(name = __v)
      def withDatatype(__v: _root_.scala.Predef.String): InferOutputTensor = copy(datatype = __v)
      def clearShape = copy(shape = _root_.scala.Seq.empty)
      def addShape(__vs: _root_.scala.Long *): InferOutputTensor = addAllShape(__vs)
      def addAllShape(__vs: Iterable[_root_.scala.Long]): InferOutputTensor = copy(shape = shape ++ __vs)
      def withShape(__v: _root_.scala.Seq[_root_.scala.Long]): InferOutputTensor = copy(shape = __v)
      def clearParameters = copy(parameters = _root_.scala.collection.immutable.Map.empty)
      def addParameters(__vs: (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter) *): InferOutputTensor = addAllParameters(__vs)
      def addAllParameters(__vs: Iterable[(_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)]): InferOutputTensor = copy(parameters = parameters ++ __vs)
      def withParameters(__v: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]): InferOutputTensor = copy(parameters = __v)
      def getContents: org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents = contents.getOrElse(org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents.defaultInstance)
      def clearContents: InferOutputTensor = copy(contents = _root_.scala.None)
      def withContents(__v: org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents): InferOutputTensor = copy(contents = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = name
            if (__t != "") __t else null
          }
          case 2 => {
            val __t = datatype
            if (__t != "") __t else null
          }
          case 3 => shape
          case 4 => parameters.iterator.map(org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor._typemapper_parameters.toBase(_)).toSeq
          case 5 => contents.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(name)
          case 2 => _root_.scalapb.descriptors.PString(datatype)
          case 3 => _root_.scalapb.descriptors.PRepeated(shape.iterator.map(_root_.scalapb.descriptors.PLong(_)).toVector)
          case 4 => _root_.scalapb.descriptors.PRepeated(parameters.iterator.map(org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor._typemapper_parameters.toBase(_).toPMessage).toVector)
          case 5 => contents.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.type = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor
      // @@protoc_insertion_point(GeneratedMessage[org.pytorch.serve.grpc.openinference.ModelInferResponse.InferOutputTensor])
  }
  
  object InferOutputTensor extends scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor = {
      var __name: _root_.scala.Predef.String = ""
      var __datatype: _root_.scala.Predef.String = ""
      val __shape: _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Long] = new _root_.scala.collection.immutable.VectorBuilder[_root_.scala.Long]
      val __parameters: _root_.scala.collection.mutable.Builder[(_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter), _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]] = _root_.scala.collection.immutable.Map.newBuilder[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]
      var __contents: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __name = _input__.readStringRequireUtf8()
          case 18 =>
            __datatype = _input__.readStringRequireUtf8()
          case 24 =>
            __shape += _input__.readInt64()
          case 26 => {
            val length = _input__.readRawVarint32()
            val oldLimit = _input__.pushLimit(length)
            while (_input__.getBytesUntilLimit > 0) {
              __shape += _input__.readInt64()
            }
            _input__.popLimit(oldLimit)
          }
          case 34 =>
            __parameters += org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor._typemapper_parameters.toCustom(_root_.scalapb.LiteParser.readMessage[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry](_input__))
          case 42 =>
            __contents = _root_.scala.Option(__contents.fold(_root_.scalapb.LiteParser.readMessage[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor(
          name = __name,
          datatype = __datatype,
          shape = __shape.result(),
          parameters = __parameters.result(),
          contents = __contents,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor(
          name = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          datatype = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          shape = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Seq[_root_.scala.Long]]).getOrElse(_root_.scala.Seq.empty),
          parameters = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry]]).getOrElse(_root_.scala.Seq.empty).iterator.map(org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor._typemapper_parameters.toCustom(_)).toMap,
          contents = __fieldsMap.get(scalaDescriptor.findFieldByNumber(5).get).flatMap(_.as[_root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
      (__number: @_root_.scala.unchecked) match {
        case 4 => __out = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry
        case 5 => __out = org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] =
      Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]](
        _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry
      )
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor(
      name = "",
      datatype = "",
      shape = _root_.scala.Seq.empty,
      parameters = _root_.scala.collection.immutable.Map.empty,
      contents = _root_.scala.None
    )
    @SerialVersionUID(0L)
    final case class ParametersEntry(
        key: _root_.scala.Predef.String = "",
        value: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = _root_.scala.None,
        unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
        ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ParametersEntry] {
        @transient
        private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
        private[this] def __computeSerializedSize(): _root_.scala.Int = {
          var __size = 0
          
          {
            val __value = key
            if (!__value.isEmpty) {
              __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
            }
          };
          if (value.isDefined) {
            val __value = value.get
            __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
          };
          __size += unknownFields.serializedSize
          __size
        }
        override def serializedSize: _root_.scala.Int = {
          var __size = __serializedSizeMemoized
          if (__size == 0) {
            __size = __computeSerializedSize() + 1
            __serializedSizeMemoized = __size
          }
          __size - 1
          
        }
        def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
          {
            val __v = key
            if (!__v.isEmpty) {
              _output__.writeString(1, __v)
            }
          };
          value.foreach { __v =>
            val __m = __v
            _output__.writeTag(2, 2)
            _output__.writeUInt32NoTag(__m.serializedSize)
            __m.writeTo(_output__)
          };
          unknownFields.writeTo(_output__)
        }
        def withKey(__v: _root_.scala.Predef.String): ParametersEntry = copy(key = __v)
        def getValue: org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter = value.getOrElse(org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter.defaultInstance)
        def clearValue: ParametersEntry = copy(value = _root_.scala.None)
        def withValue(__v: org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter): ParametersEntry = copy(value = Option(__v))
        def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
        def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
        def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
          (__fieldNumber: @_root_.scala.unchecked) match {
            case 1 => {
              val __t = key
              if (__t != "") __t else null
            }
            case 2 => value.orNull
          }
        }
        def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
          _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
          (__field.number: @_root_.scala.unchecked) match {
            case 1 => _root_.scalapb.descriptors.PString(key)
            case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
          }
        }
        def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
        def companion: org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry.type = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry
        // @@protoc_insertion_point(GeneratedMessage[org.pytorch.serve.grpc.openinference.ModelInferResponse.InferOutputTensor.ParametersEntry])
    }
    
    object ParametersEntry extends scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry] {
      implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry] = this
      def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry = {
        var __key: _root_.scala.Predef.String = ""
        var __value: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = _root_.scala.None
        var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
        var _done__ = false
        while (!_done__) {
          val _tag__ = _input__.readTag()
          _tag__ match {
            case 0 => _done__ = true
            case 10 =>
              __key = _input__.readStringRequireUtf8()
            case 18 =>
              __value = _root_.scala.Option(__value.fold(_root_.scalapb.LiteParser.readMessage[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
            case tag =>
              if (_unknownFields__ == null) {
                _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
              }
              _unknownFields__.parseField(tag, _input__)
          }
        }
        org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry(
            key = __key,
            value = __value,
            unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
        )
      }
      implicit def messageReads: _root_.scalapb.descriptors.Reads[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry] = _root_.scalapb.descriptors.Reads{
        case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
          _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
          org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry(
            key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
            value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]])
          )
        case _ => throw new RuntimeException("Expected PMessage")
      }
      def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.javaDescriptor.getNestedTypes().get(0)
      def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.scalaDescriptor.nestedMessages(0)
      def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
        var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
        (__number: @_root_.scala.unchecked) match {
          case 2 => __out = org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter
        }
        __out
      }
      lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
      def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
      lazy val defaultInstance = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry(
        key = "",
        value = _root_.scala.None
      )
      implicit class ParametersEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry](_l) {
        def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
        def value: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = field(_.getValue)((c_, f_) => c_.copy(value = _root_.scala.Option(f_)))
        def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]] = field(_.value)((c_, f_) => c_.copy(value = f_))
      }
      final val KEY_FIELD_NUMBER = 1
      final val VALUE_FIELD_NUMBER = 2
      @transient
      implicit val keyValueMapper: _root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)] =
        _root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)](__m => (__m.key, __m.getValue))(__p => org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry(__p._1, Some(__p._2)))
      def of(
        key: _root_.scala.Predef.String,
        value: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]
      ): _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry = _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry(
        key,
        value
      )
      // @@protoc_insertion_point(GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.ModelInferResponse.InferOutputTensor.ParametersEntry])
    }
    
    implicit class InferOutputTensorLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor](_l) {
      def name: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.name)((c_, f_) => c_.copy(name = f_))
      def datatype: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.datatype)((c_, f_) => c_.copy(datatype = f_))
      def shape: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.scala.Long]] = field(_.shape)((c_, f_) => c_.copy(shape = f_))
      def parameters: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]] = field(_.parameters)((c_, f_) => c_.copy(parameters = f_))
      def contents: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents] = field(_.getContents)((c_, f_) => c_.copy(contents = _root_.scala.Option(f_)))
      def optionalContents: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents]] = field(_.contents)((c_, f_) => c_.copy(contents = f_))
    }
    final val NAME_FIELD_NUMBER = 1
    final val DATATYPE_FIELD_NUMBER = 2
    final val SHAPE_FIELD_NUMBER = 3
    final val PARAMETERS_FIELD_NUMBER = 4
    final val CONTENTS_FIELD_NUMBER = 5
    @transient
    private[open_inference_grpc] val _typemapper_parameters: _root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)] = implicitly[_root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)]]
    def of(
      name: _root_.scala.Predef.String,
      datatype: _root_.scala.Predef.String,
      shape: _root_.scala.Seq[_root_.scala.Long],
      parameters: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter],
      contents: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferTensorContents]
    ): _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor = _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor(
      name,
      datatype,
      shape,
      parameters,
      contents
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.ModelInferResponse.InferOutputTensor])
  }
  
  @SerialVersionUID(0L)
  final case class ParametersEntry(
      key: _root_.scala.Predef.String = "",
      value: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = _root_.scala.None,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ParametersEntry] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = key
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
          }
        };
        if (value.isDefined) {
          val __value = value.get
          __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = key
          if (!__v.isEmpty) {
            _output__.writeString(1, __v)
          }
        };
        value.foreach { __v =>
          val __m = __v
          _output__.writeTag(2, 2)
          _output__.writeUInt32NoTag(__m.serializedSize)
          __m.writeTo(_output__)
        };
        unknownFields.writeTo(_output__)
      }
      def withKey(__v: _root_.scala.Predef.String): ParametersEntry = copy(key = __v)
      def getValue: org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter = value.getOrElse(org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter.defaultInstance)
      def clearValue: ParametersEntry = copy(value = _root_.scala.None)
      def withValue(__v: org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter): ParametersEntry = copy(value = Option(__v))
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 1 => {
            val __t = key
            if (__t != "") __t else null
          }
          case 2 => value.orNull
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 1 => _root_.scalapb.descriptors.PString(key)
          case 2 => value.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry.type = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry
      // @@protoc_insertion_point(GeneratedMessage[org.pytorch.serve.grpc.openinference.ModelInferResponse.ParametersEntry])
  }
  
  object ParametersEntry extends scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry = {
      var __key: _root_.scala.Predef.String = ""
      var __value: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = _root_.scala.None
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __key = _input__.readStringRequireUtf8()
          case 18 =>
            __value = _root_.scala.Option(__value.fold(_root_.scalapb.LiteParser.readMessage[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry(
          key = __key,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry(
          key = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]])
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.javaDescriptor.getNestedTypes().get(1)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.scalaDescriptor.nestedMessages(1)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[?] = {
      var __out: _root_.scalapb.GeneratedMessageCompanion[?] = null
      (__number: @_root_.scala.unchecked) match {
        case 2 => __out = org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter
      }
      __out
    }
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[? <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[?] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry(
      key = "",
      value = _root_.scala.None
    )
    implicit class ParametersEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry](_l) {
      def key: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.key)((c_, f_) => c_.copy(key = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter] = field(_.getValue)((c_, f_) => c_.copy(value = _root_.scala.Option(f_)))
      def optionalValue: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val KEY_FIELD_NUMBER = 1
    final val VALUE_FIELD_NUMBER = 2
    @transient
    implicit val keyValueMapper: _root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)] =
      _root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)](__m => (__m.key, __m.getValue))(__p => org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry(__p._1, Some(__p._2)))
    def of(
      key: _root_.scala.Predef.String,
      value: _root_.scala.Option[org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]
    ): _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry = _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry(
      key,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.ModelInferResponse.ParametersEntry])
  }
  
  implicit class ModelInferResponseLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse](_l) {
    def modelName: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.modelName)((c_, f_) => c_.copy(modelName = f_))
    def modelVersion: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.modelVersion)((c_, f_) => c_.copy(modelVersion = f_))
    def id: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def parameters: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter]] = field(_.parameters)((c_, f_) => c_.copy(parameters = f_))
    def outputs: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor]] = field(_.outputs)((c_, f_) => c_.copy(outputs = f_))
    def rawOutputContents: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[_root_.com.google.protobuf.ByteString]] = field(_.rawOutputContents)((c_, f_) => c_.copy(rawOutputContents = f_))
  }
  final val MODEL_NAME_FIELD_NUMBER = 1
  final val MODEL_VERSION_FIELD_NUMBER = 2
  final val ID_FIELD_NUMBER = 3
  final val PARAMETERS_FIELD_NUMBER = 4
  final val OUTPUTS_FIELD_NUMBER = 5
  final val RAW_OUTPUT_CONTENTS_FIELD_NUMBER = 6
  @transient
  private[open_inference_grpc] val _typemapper_parameters: _root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)] = implicitly[_root_.scalapb.TypeMapper[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.ParametersEntry, (_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter)]]
  def of(
    modelName: _root_.scala.Predef.String,
    modelVersion: _root_.scala.Predef.String,
    id: _root_.scala.Predef.String,
    parameters: _root_.scala.collection.immutable.Map[_root_.scala.Predef.String, org.pytorch.serve.grpc.openinference.open_inference_grpc.InferParameter],
    outputs: _root_.scala.Seq[org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse.InferOutputTensor],
    rawOutputContents: _root_.scala.Seq[_root_.com.google.protobuf.ByteString]
  ): _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse = _root_.org.pytorch.serve.grpc.openinference.open_inference_grpc.ModelInferResponse(
    modelName,
    modelVersion,
    id,
    parameters,
    outputs,
    rawOutputContents
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[org.pytorch.serve.grpc.openinference.ModelInferResponse])
}
